### ISSUE TITLE
It looks like ios is not implemented

### ISSUE THREAD

**Issue by ryanhz** [dukhanov/flutter-nfc-plugin#3]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getNfcState on channel nfc_plugin_method_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>                                               
#1      NfcPlugin.nfcState (package:flutter_nfc_plugin/nfc_plugin.dart:29:8)
#2      _MyAppState.initPlatformState (package:nfc_plugin_example/main.dart:38:35)
<asynchronous suspension>                                               
#3      _MyAppState.initState (package:nfc_plugin_example/main.dart:31:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)

**Comment by dukhanov** [comment]
Yes.  iOS is not implemented.

**Comment by ryanhz** [comment]
oh, yes, because Apple is really sucks.
