### ISSUE TITLE
Can't read tag id if the message is null

### ISSUE THREAD

**Issue by movieator** [dukhanov/flutter-nfc-plugin#5]
Hi, i' m trying to read an nfc card wich has not any message and the error i get is: 

> D/FlutterNfcPlugin( 6804): callback: onTagDiscovered {error=Cannot parse NDEF message: java.lang.IllegalStateException: ndef must not be null, message=null}

In other android applications in play store, i can get the tag id (serial number) although the tag has no messages (null).

How can i implement this? 

Thanks!

**Comment by dukhanov** [comment]
It is an issue of the plugin

**Comment by dukhanov** [comment]
Fixed in the v0.0.5
